In [ ]:
# Frame conversion test
import numpy as np
import os
# Set working directory to root folder
os.chdir("H:/tanne/Documents/PROTOS")

# Import utility functions
from utils.frame_convertions.rel_to_inertial_functions import LVLH_basis_vectors, LVLH_DCM, inertial_to_LVLH, rel_vector_to_inertial

# Chief inertial state (km, km/s)
rc_N = np.array([-6685.20926, 601.51244, 3346.06634])   # km
vc_N = np.array([-1.74294, -6.70242, -2.27739])        # km/s

# Deputy relative state in Hill frame (km, km/s)
rho_H = np.array([-81.22301, 248.14201, 94.95904])     # km
rho_dot_H = np.array([0.47884, 0.14857, 0.13577])      # km/s


# Compute the LVLH basis vectors
r_hat, theta_hat, h_hat = LVLH_basis_vectors(rc_N, vc_N)
print("r_hat:", r_hat)
print("theta_hat:", theta_hat)
print("h_hat:", h_hat)

# Compute the DCM from inertial to LVLH
C_LVLH_inertial = LVLH_DCM(rc_N, vc_N)
print("DCM from inertial to LVLH:\n", C_LVLH_inertial)

# Convert the chief inertial state to LVLH
rc_H, vc_H = inertial_to_LVLH(rc_N, vc_N)
print("Chief position in LVLH :", rc_H)
print("Chief velocity in LVLH:", vc_H)


# Compute inertial state of the deputy
rd_N, vd_N = rel_vector_to_inertial(rho_H, rho_dot_H, rc_N, vc_N)
print("Deputy position in inertial :", rd_N)
print("Deputy velocity in inertial:", vd_N)




r_hat: [-0.89136123  0.08020166  0.44614218]
theta_hat: [-0.23907988 -0.91937605 -0.31239156]
h_hat: [ 0.38511811 -0.38511735  0.83867078]
DCM from inertial to LVLH:
 [[-0.89136123  0.08020166  0.44614218]
 [-0.23907988 -0.91937605 -0.31239156]
 [ 0.38511811 -0.38511735  0.83867078]]
Chief position in LVLH : [ 7.50000000e+03 -7.59615060e-14  2.46881334e-13]
Chief velocity in LVLH: [ 4.21299560e-06 -8.88178420e-16 -1.24485561e-16]
Deputy position in inertial : [-6635.56553292   330.29202509  3311.95123111]
Deputy velocity in inertial: [-1.91912006 -6.79965453 -2.07925096]
